python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky1/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky2/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky3/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky4/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky5/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky6/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky7/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky8/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky9/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky10/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky11/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky12/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky13/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky14/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky15/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky16/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky17/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky18/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky19/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky20/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky21/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky22/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky23/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky24/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky25/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky26/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky27/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky28/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky29/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky30/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky31/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky32/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky33/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky34/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky35/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky36/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky37/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky38/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky39/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky40/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky41/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky42/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky43/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky44/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky45/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky46/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky47/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky48/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky49/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/Bohachevsky/bohachevsky50/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price1/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price2/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price3/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price4/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price5/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price6/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price7/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price8/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price9/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price10/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price11/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price12/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price13/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price14/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price15/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price16/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price17/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price18/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price19/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price20/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price21/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price22/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price23/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price24/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price25/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price26/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price27/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price28/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price29/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price30/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price31/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price32/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price33/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price34/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price35/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price36/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price37/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price38/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price39/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price40/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price41/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price42/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price43/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price44/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price45/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price46/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price47/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price48/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price49/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/goldstein_price/goldstein_price50/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann3/hartmann3_10/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann3/hartmann3_22/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann3/hartmann3_42/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann3/hartmann3_44/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_1/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_2/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_3/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_4/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_5/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_6/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_7/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_8/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_9/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_10/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_11/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_12/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_13/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_14/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_15/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_16/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_17/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_18/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_19/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_20/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_21/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_22/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_23/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_24/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_25/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_26/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_27/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_28/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_29/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_30/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_31/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_32/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_33/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_34/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_35/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_36/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_37/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_38/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_39/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_40/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_41/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_42/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_43/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_44/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_45/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_46/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_47/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_48/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_49/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/hartmann6/hartmann6_50/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock1/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock2/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock3/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock4/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock5/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock6/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock7/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock8/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock9/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock10/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock11/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock12/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock13/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock14/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock15/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock16/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock17/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock18/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock19/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock20/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock21/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock22/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock23/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock24/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock25/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock26/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock27/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock28/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock29/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock30/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock31/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock32/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock33/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock34/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock35/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock36/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock37/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock38/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock39/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock40/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock41/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock42/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock43/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock44/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock45/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock46/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock47/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock48/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock49/config.pb
python /home/mansurm/spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 /home/mansurm/Experiments/rosenbrock/rosenbrock50/config.pb
