python /ihome/kleinaa/devel/git/learning_curve_prediction/lc_prediction/experiments/predictability_partially.py with model_type=gp dataset=fcnet n_configs=4096 observed=10
python /ihome/kleinaa/devel/git/learning_curve_prediction/lc_prediction/experiments/predictability_partially.py with model_type=gp dataset=fcnet n_configs=4096 observed=20
python /ihome/kleinaa/devel/git/learning_curve_prediction/lc_prediction/experiments/predictability_partially.py with model_type=gp dataset=fcnet n_configs=4096 observed=30
python /ihome/kleinaa/devel/git/learning_curve_prediction/lc_prediction/experiments/predictability_partially.py with model_type=gp dataset=fcnet n_configs=4096 observed=40
python /ihome/kleinaa/devel/git/learning_curve_prediction/lc_prediction/experiments/predictability_partially.py with model_type=gp dataset=fcnet n_configs=4096 observed=50
python /ihome/kleinaa/devel/git/learning_curve_prediction/lc_prediction/experiments/predictability_partially.py with model_type=gp dataset=fcnet n_configs=4096 observed=60
python /ihome/kleinaa/devel/git/learning_curve_prediction/lc_prediction/experiments/predictability_partially.py with model_type=gp dataset=fcnet n_configs=4096 observed=70
python /ihome/kleinaa/devel/git/learning_curve_prediction/lc_prediction/experiments/predictability_partially.py with model_type=gp dataset=fcnet n_configs=4096 observed=80
python /ihome/kleinaa/devel/git/learning_curve_prediction/lc_prediction/experiments/predictability_partially.py with model_type=gp dataset=fcnet n_configs=4096 observed=90
