#Forrester
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester1/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester2/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester3/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester4/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester5/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester6/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester7/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester8/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester9/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester10/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester11/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester12/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester13/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester14/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester15/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester16/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester17/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester18/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester19/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester20/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester21/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester22/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester23/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester24/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester25/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester26/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester27/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester28/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester29/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/forrester/forrester30/config.pb
#goldstein_price
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price1/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price2/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price3/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price4/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price5/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price6/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price7/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price8/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price9/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price10/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price11/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price12/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price13/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price14/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price15/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price16/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price17/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price18/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price19/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price20/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price21/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price22/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price23/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price24/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price25/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price26/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price27/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price28/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price29/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/goldstein_price/goldstein_price30/config.pb
#Hartmann3
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_1/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_2/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_3/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_4/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_5/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_6/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_7/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_8/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_9/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_10/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_11/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_12/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_13/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_14/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_15/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_16/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_17/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_18/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_19/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_20/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_21/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_22/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_23/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_24/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_25/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_26/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_27/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_28/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_29/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann3/hartmann3_30/config.pb
#hartmann6
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_1/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_2/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_3/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_4/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_5/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_6/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_7/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_8/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_9/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_10/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_11/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_12/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_13/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_14/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_15/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_16/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_17/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_18/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_19/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_20/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_21/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_22/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_23/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_24/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_25/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_26/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_27/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_28/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_29/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/hartmann6/hartmann6_30/config.pb
#rosenbrock
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock1/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock2/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock3/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock4/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock5/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock6/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock7/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock8/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock9/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock10/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock11/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock12/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock13/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock14/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock15/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock16/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock17/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock18/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock19/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock20/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock21/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock22/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock23/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock24/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock25/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock26/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock27/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock28/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock29/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/rosenbrock/rosenbrock30/config.pb
#sin_one
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one1/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one2/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one3/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one4/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one5/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one6/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one7/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one8/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one9/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one10/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one11/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one12/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one13/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one14/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one15/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one16/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one17/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one18/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one19/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one20/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one21/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one22/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one23/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one24/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one25/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one26/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one27/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one28/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one29/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_one/sin_one30/config.pb
#sin_two
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two1/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two2/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two3/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two4/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two5/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two6/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two7/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two8/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two9/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two10/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two11/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two12/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two13/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two14/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two15/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two16/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two17/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two18/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two19/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two20/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two21/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two22/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two23/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two24/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two25/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two26/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two27/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two28/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two29/config.pb
python spearmint/spearmint/spearmint/main.py --driver=local --method=GPEIOptChooser --method-args=noiseless=1 Experiments/sin_two/sin_two30/config.pb

